services:
  # Backend API Service
  - type: web
    name: aman-project-backend
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    
  # Frontend Static Site
  - type: web
    name: aman-project-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
        # Set this in Render Dashboard to: https://aman-project-backend.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

